# Generated by Django 5.1.5 on 2025-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="icons",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
