# Generated by Django 5.1.5 on 2025-02-11 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_family_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("black", "Schwarz"),
                            ("white", "Weiß"),
                            ("colored", "Colored"),
                        ],
                        default="colored",
                        max_length=10,
                        verbose_name="Design",
                    ),
                ),
                (
                    "icons",
                    models.CharField(
                        choices=[
                            ("black", "Schwarz"),
                            ("white", "Weiß"),
                            ("colored", "Colored"),
                        ],
                        default="colored",
                        max_length=10,
                        verbose_name="Icons",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
