# Generated by Django 5.1.5 on 2025-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usersettings_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="icons",
            field=models.CharField(
                default="default", max_length=50, verbose_name="Icons"
            ),
        ),
    ]
